### ISSUE TITLE
Unclear error when using the sd-webui-frequency-separation extension

### ISSUE THREAD

**Issue by Konpr** [w-e-w/sd-webui-hires-fix-tweaks#11]
https://github.com/thavocado/sd-webui-frequency-separation

*** Error running setup: /home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/scripts/sd-webui-hires-fix-tweaks.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/A1111/modules/scripts.py", line 994, in setup_scrips
        script.setup(p, *script_args)
      File "/home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/scripts/sd-webui-hires-fix-tweaks.py", line 28, in setup
        self.hr_output_dir.setup(p, *args)
      File "/home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/hires_fix_tweaks/hr_modules/hr_output_dir.py", line 15, in setup
        p.enable_hr
    AttributeError: 'StableDiffusionProcessingImg2ImgOv' object has no attribute 'enable_hr'

*** Error running process: /home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/scripts/sd-webui-hires-fix-tweaks.py
    Traceback (most recent call last):
      File "/home/studio-lab-user/A1111/modules/scripts.py", line 832, in process
        script.process(p, *script_args)
      File "/home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/scripts/sd-webui-hires-fix-tweaks.py", line 35, in process
        self.hires_batch_seed.process(p, *args)
      File "/home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/hires_fix_tweaks/hr_modules/hr_batch_seed.py", line 154, in process
        self.enable = p.enable_hr and (self.enable_hr_seed or self.update_progress_bar)
    AttributeError: 'StableDiffusionProcessingImg2ImgOv' object has no attribute 'enable_hr'

      File "/home/studio-lab-user/A1111/modules/scripts.py", line 864, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "/home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/scripts/sd-webui-hires-fix-tweaks.py", line 42, in process_batch
        self.hires_cfg_scale.process_batch(p, *args, **kwargs)
      File "/home/studio-lab-user/A1111/extensions/sd-webui-hires-fix-tweaks/hires_fix_tweaks/hr_modules/hr_cfg_scale.py", line 13, in process_batch
        self.apply_hr_cfg_scale = p.hr_cfg_scale != 0 and p.hr_cfg_scale != self.first_pass_cfg_scale
    AttributeError: 'StableDiffusionProcessingImg2ImgOv' object has no attribute 'hr_cfg_scale'. Did you mean: 'cfg_scale'?

**Comment by w-e-w** [comment]
are you a bot?

**Comment by Konpr** [comment]
> are you a bot?

nope

**Comment by w-e-w** [comment]
do you mind searching for "bug report etiquette"

**Comment by Konpr** [comment]
> do you mind searching for "bug report etiquette"

oh....

**Comment by Konpr** [comment]
Sorry

**Comment by w-e-w** [comment]
imagine from my perspective
I suddenly got this buf report
the title being is an error when using with another extension
I look at this extension up it's an extension that has been created like 6 hours ago
in the description there's a bunch of nonsensical emojis and lots of outputs of other things
and a bunch of error trace

I'm able to see what's triggers the error apparently is something to do with this
```
AttributeError: 'StableDiffusionProcessingImg2ImgOv' object has no attribute 'enable_hr'
```
`StableDiffusionProcessingImg2ImgOv` is this is not a thing I have seen before
I did a quick Google search and found that the only reference to it seems to be in https://github.com/RGX650/sd-webui-bmab-SDNEXT

what even is this
what should I do this information should I go install this software?

---

some general guidelines on how to write a effective bug report


describe what has happened (in human words not log spam)

describe your situation how did you end up in the situation
you want to give as many information as possible / necessary
you want to let the developer able to recreate your situation
for anyone to solve an issue they first need to be reproduced the issue themselves

**Comment by w-e-w** [comment]
by the way I did a quick test of https://github.com/thavocado/sd-webui-frequency-separation

I don't think this extension works with a1111 yet
even they say on read me it works with `v1.9.4` but from my test it dose not
nor dose it workl with `v1.10.1` or `dev`

considering that this extension is literally been on github for about 6 hours and he has made some updates in the last hour I would say this exception is still in development and should not be used at this stage

```py
Traceback (most recent call last):
  File "B:\GitHub\stable-diffusion-webui\extensions\sd-webui-frequency-separation\scripts\frequency_separation.py", line 1207, in encode_image_to_latent
    latent = latent * p.sd_model.scale_factor
             ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

I sey come back in a week or tow  see if things have stable down

---

yes I did have see the 
```py
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'
```
when my extention is enabled with it I think I have an idea of what's going on but at this point I'm not going to deal with it

> but I have no idea what is `StableDiffusionProcessingImg2ImgOv` (with the `Ov` suffix)

**Comment by w-e-w** [comment]
I made a fix https://github.com/w-e-w/sd-webui-hires-fix-tweaks/commit/28902f742a795afc31d86641ad85466afdd280e6
once you update this extention the error will no longe trigger

the cause of this issue is  `sd-webui-frequency-separation` swaps the `p` object from `txt2img` to `img2img` pipline, and so when my code tries to access attributes exclusive `txt2img` such as `enable_hr` it raise `AttributeError`

so I use getattr to prevent the error form trigging the issue

**Comment by Konpr** [comment]
> I made a fix [28902f7](https://github.com/w-e-w/sd-webui-hires-fix-tweaks/commit/28902f742a795afc31d86641ad85466afdd280e6) once you update this extention the error will no longe trigger
> 
> the cause of this issue is `sd-webui-frequency-separation` swaps the `p` object from `txt2img` to `img2img` pipline, and so when my code tries to access attributes exclusive `txt2img` such as `enable_hr` it raise `AttributeError`
> 
> so I use getattr to prevent the error form trigging the issue

Thanks you very much 🙏.

The extensions turned out to be interesting enough to give the picture not only more details, but also, with use close up, upper body more of a feeling that the character is alive.

**Comment by Konpr** [comment]
> imagine from my perspective I suddenly got this buf report the title being is an error when using with another extension I look at this extension up it's an extension that has been created like 6 hours ago in the description there's a bunch of nonsensical emojis and lots of outputs of other things and a bunch of error trace
> 
> I'm able to see what's triggers the error apparently is something to do with this
> 
> ```
> AttributeError: 'StableDiffusionProcessingImg2ImgOv' object has no attribute 'enable_hr'
> ```
> 
> `StableDiffusionProcessingImg2ImgOv` is this is not a thing I have seen before I did a quick Google search and found that the only reference to it seems to be in https://github.com/RGX650/sd-webui-bmab-SDNEXT
> 
> what even is this what should I do this information should I go install this software?
> 
> some general guidelines on how to write a effective bug report
> 
> describe what has happened (in human words not log spam)
> 
> describe your situation how did you end up in the situation you want to give as many information as possible / necessary you want to let the developer able to recreate your situation for anyone to solve an issue they first need to be reproduced the issue themselves

Yes... I'm just pretty quick when it comes to new extensions.
I was a little worried, so I decided to just show the whole line of code.

**Comment by Konpr** [comment]
It's just that the art was really good.

![Image](https://github.com/user-attachments/assets/77b27961-3023-4de4-920b-e34ac71a2fe8)
![Image](https://github.com/user-attachments/assets/7b401b1a-899f-4857-b861-2e7bf3bf6e71)
![Image](https://github.com/user-attachments/assets/8a960594-491e-4c6a-841a-13942e30c6f3)
![Image](https://github.com/user-attachments/assets/071f1b0b-97c6-4353-b08c-67ec3f9b3885)
![Image](https://github.com/user-attachments/assets/839efdc2-6048-44ab-853d-5040680e0832)
![Image](https://github.com/user-attachments/assets/12b51165-6b11-449a-8898-49778c9f2682)
